################################################################################
# Environment script generated by ilcsoft-install on Fri Jul 31 13:20:34 2015
# for the installation located at [ /cvmfs/ilc.desy.de/sw/x86_64_gcc48_sl6/v01-17-08 ]
################################################################################

SET( ILC_HOME "/cvmfs/ilc.desy.de/sw/x86_64_gcc48_sl6/v01-17-08" CACHE PATH "Path to ILC Software" FORCE)
MARK_AS_ADVANCED( ILC_HOME )

SET( CMAKE_PREFIX_PATH 
	${ILC_HOME}/lccd/v01-03;
	${ILC_HOME}/Marlin/v01-07;
	${ILC_HOME}/MarlinDD4hep/v00-01;
	${ILC_HOME}/DDMarlinPandora/v00-01;
	${ILC_HOME}/MarlinUtil/v01-10;
	${ILC_HOME}/Mokka/mokka-08-05;
	${ILC_HOME}/MarlinReco/v01-13;
	${ILC_HOME}/PandoraAnalysis/v01-00-01;
	${ILC_HOME}/PandoraPFANew/v02-00-00;
	${ILC_HOME}/MarlinPandora/v02-00-00;
	${ILC_HOME}/LCFIVertex/v00-07;
	${ILC_HOME}/CEDViewer/v01-10;
	${ILC_HOME}/Overlay/v00-14;
	${ILC_HOME}/FastJetClustering/v00-02;
	${ILC_HOME}/MarlinFastJet/v00-02;
	${ILC_HOME}/LCTuple/v01-04;
	${ILC_HOME}/MarlinKinfit/v00-01-05;
	${ILC_HOME}/MarlinTrk/v02-00-01;
	${ILC_HOME}/KiTrack/v01-06;
	${ILC_HOME}/KiTrackMarlin/v01-07;
	${ILC_HOME}/MarlinTrkProcessors/v02-01;
	${ILC_HOME}/ILDPerformance/v00-01;
	${ILC_HOME}/Clupatra/v00-12;
	${ILC_HOME}/Physsim/v00-02;
	${ILC_HOME}/FCalClusterer/v00-01;
	${ILC_HOME}/LCFIPlus/v00-05-03;
	${ILC_HOME}/ForwardTracking/v01-08;
	${ILC_HOME}/pathfinder/v00-06;
	${ILC_HOME}/MarlinTPC/v01-00;
	${ILC_HOME}/bbq/v00-01-02;
	${ILC_HOME}/Garlic/v3.0.3;
	${ILC_HOME}/RAIDA/v01-06-02;
	${ILC_HOME}/KalTest/v02-00;
	${ILC_HOME}/KalDet/v01-13-02;
	${ILC_HOME}/GBL/V01-16-04;
	${ILC_HOME}/xercesc/3.1.2;
	${ILC_HOME}/heppdt/3.04.01;
	${ILC_HOME}/gdml/ilcsoft-v01-17-07;
	${ILC_HOME}/lcdd/ilcsoft-v01-17-07;
	${ILC_HOME}/slic/ilcsoft-v01-17-07;
	${ILC_HOME}/slicPandora/ilcsoft-v01-17-07;
	${ILC_HOME}/DD4hep/v00-14;
	${ILC_HOME}/lcgeo/v00-05;
	${ILC_HOME}/aidaTT/v00-02;
	${ILC_HOME}/DDKalTest/v00-02;
	${ILC_HOME}/DD4hepExamples/v00-14;
	${ILC_HOME}/CED/v01-09-01;
	${ILC_HOME}/lcio/v02-06;
	${ILC_HOME}/gear/v01-04-02;
	${ILC_HOME}/FastJet/3.1.2;
	${ILC_HOME}/root/5.34.30;
	${ILC_HOME}/CLHEP/2.1.4.1;
	${ILC_HOME}/gsl/1.14;
	${ILC_HOME}/QT/4.7.4;
	${ILC_HOME}/geant4/10.01;
	${ILC_HOME}/CondDBMySQL/CondDBMySQL_ILC-0-9-6;
	${ILC_HOME}/cernlib/2006;
	${ILC_HOME}/mysql/5.0.45;
	${ILC_HOME}/ilcutil/v01-02-01;
	/afs/desy.de/project/ilcsoft/sw/boost/1.58.0;
CACHE PATH "CMAKE_PREFIX_PATH" FORCE )


