################################################################################
# Environment script generated by ilcsoft-install on Tue Dec  3 17:50:33 2013
# for the installation located at [ /afs/desy.de/project/ilcsoft/sw/x86_64_gcc44_sl6/v01-16-02 ]
################################################################################

SET( ILC_HOME "/afs/desy.de/project/ilcsoft/sw/x86_64_gcc44_sl6/v01-16-02" CACHE PATH "Path to ILC Software" FORCE)
MARK_AS_ADVANCED( ILC_HOME )

SET( CMAKE_PREFIX_PATH 
	${ILC_HOME}/lccd/v01-02;
	${ILC_HOME}/Marlin/v01-04;
	${ILC_HOME}/MarlinUtil/v01-05-03;
	${ILC_HOME}/Mokka/mokka-08-00-03;
	${ILC_HOME}/MarlinReco/v01-06;
	${ILC_HOME}/PandoraAnalysis/v00-04;
	${ILC_HOME}/PandoraPFANew/v00-09;
	${ILC_HOME}/MarlinPandora/v00-09-02;
	${ILC_HOME}/LCFIVertex/v00-06-01;
	${ILC_HOME}/CEDViewer/v01-06-01;
	${ILC_HOME}/Overlay/v00-13;
	${ILC_HOME}/FastJetClustering/v00-02;
	${ILC_HOME}/MarlinFastJet/v00-01;
	${ILC_HOME}/LCTuple/v01-01;
	${ILC_HOME}/MarlinKinfit/v00-01-02;
	${ILC_HOME}/MarlinTrk/v01-10-01;
	${ILC_HOME}/KiTrack/v01-04;
	${ILC_HOME}/KiTrackMarlin/v01-04;
	${ILC_HOME}/MarlinTrkProcessors/v01-09;
	${ILC_HOME}/Clupatra/v00-09-01;
	${ILC_HOME}/LCFIPlus/v00-05-02;
	${ILC_HOME}/ForwardTracking/v01-07;
	${ILC_HOME}/pathfinder/v00-03;
	${ILC_HOME}/MarlinTPC/v00-11;
	${ILC_HOME}/bbq/v00-01-02;
	${ILC_HOME}/Garlic/v2.10.1;
	${ILC_HOME}/RAIDA/v01-06-02;
	${ILC_HOME}/KalTest/v01-05-02;
	${ILC_HOME}/KalDet/v01-11;
	${ILC_HOME}/CED/v01-07;
	${ILC_HOME}/lcio/v02-03-03;
	${ILC_HOME}/gear/v01-02-02;
	${ILC_HOME}/FastJet/2.4.2;
	${ILC_HOME}/root/5.28.00f;
	${ILC_HOME}/CLHEP/2.1.1.0;
	${ILC_HOME}/gsl/1.14;
	${ILC_HOME}/QT/4.7.4;
	${ILC_HOME}/geant4/9.5.p02;
	${ILC_HOME}/CondDBMySQL/CondDBMySQL_ILC-0-9-5;
	${ILC_HOME}/cernlib/2006;
	${ILC_HOME}/mysql/5.0.45;
	${ILC_HOME}/java/1.6.0;
	${ILC_HOME}/ilcutil/v01-00;
CACHE PATH "CMAKE_PREFIX_PATH" FORCE )


